name = "LeanMutator"
version = "0.1.0"
defaultTargets = ["leanmutator"]
keywords = ["mutation-testing", "testing", "lean4"]
description = "Mutation testing tool for Lean 4"

[[require]]
name = "Cli"
scope = "leanprover"
git = "https://github.com/leanprover/lean4-cli"
rev = "main"

[[lean_lib]]
name = "LeanMutator"

[[lean_exe]]
name = "leanmutator"
root = "Main"
